### ISSUE TITLE
How to test

### ISSUE THREAD

**Issue by ronsoohyeong** [lucasxlu/ComboLoss#1]
Hi, 
thanks for sharing your work.
In your code, I can find the training code and the pre-trained model, but I wonder if you can kindly share the test code that uses your pre-trained model.

Thanks in advance. BR.

**Comment by lucasxlu** [comment]
I have released inference code, please refer to [inference.py](https://github.com/lucasxlu/ComboLoss/blob/master/main/inference.py).
